version: "3"
volumes:
  hausordner-files:
  admin-files:
services:
  samba:
    build:
      context: contrib/samba
    command: -u "$ADMIN_USER;$ADMIN_PASS;1111"
             -u "$HAUSORDNER_USER;$HAUSORDNER_PASS;2222"
             -s "hausordner;/srv/hausordner-files;yes;no;no;all;none;;Hausordner"
             -s "admin;/srv/admin-files;yes;no;no;$ADMIN_USER;none;;Admin Ordner"
             -n
             -g "force user ="
             -r
    volumes:
      - hausordner-files:/srv/hausordner-files
      - admin-files:/srv/admin-files
    ports:
      - "139:139"
      - "445:445"
      - "137-138:137-138/udp"
  bargate:
    build:
      context: bargate
    image: bargate
    volumes:
      - "./bargate/bargate.conf:/etc/bargate.conf"
      - "./bargate/shares.conf:/etc/bargate/shares.conf"
      - "./bargate/templates:/etc/bargate/templates"
    ports:
      - "80:5000"
    depends_on:
      - samba
  redis:
    image: redis:alpine

