version: "3"
volumes:
  hausordner-files:
services:
  samba:
    build:
      context: contrib/samba
    command: -u "$HAUSORDNER_USER;$HAUSORDNER_PASS;2222"
             -s "hausordner;/srv/hausordner-files;yes;no;no;all;none;;Hausordner"
             -g "force user ="
             -r
    volumes:
      - hausordner-files:/srv/hausordner-files
    ports:
      - "139:139"
      - "445:445"
      - "137-138:137-138/udp"
    depends_on:
      - prepare
  web:
    build:
      context: nginx
    volumes:
      - hausordner-files:/srv/hausordner-files
    ports:
      - "80:80"
    depends_on:
      - php-handler-hausordner
    environment:
      HAUSORDNER_USER: user
      HAUSORDNER_PASS: pass
      ADMIN_USER: admin
      ADMIN_PASS: pass
  php-handler-hausordner:
    build:
      context: php
      args:
        UID: "2222"
        USER_NAME: "krause"
    volumes:
      - hausordner-files:/srv/hausordner-files
    depends_on:
      - prepare
  prepare:
    image: alpine
    command: "chown -R 2222:2222 /srv/hausordner-files"
    volumes:
      - hausordner-files:/srv/hausordner-files

